security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            entry_point: jwt
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/check, roles: PUBLIC_ACCESS }
        - { path: ^/api/users/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api/google-sheets/info, roles: PUBLIC_ACCESS }
        - { path: ^/api/google-sheets/data, roles: PUBLIC_ACCESS }
        - { path: ^/api/google-sheets/all, roles: PUBLIC_ACCESS }
        - { path: ^/api/google-sheets/players, roles: PUBLIC_ACCESS }
        - { path: ^/api/google-sheets/matches, roles: PUBLIC_ACCESS }
        - { path: ^/api/articles, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/blocks, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/welcome, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/themes, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/cod/players, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/valo/players, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/cs2/players, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        ROLE_SUBSCRIBER: ROLE_VISITOR
        ROLE_AUTHOR: ROLE_SUBSCRIBER
        ROLE_EDITOR: ROLE_AUTHOR
        ROLE_DESIGNER: ROLE_USER
        ROLE_PROVIDER: ROLE_USER
        ROLE_ADMIN: [ROLE_EDITOR, ROLE_DESIGNER, ROLE_PROVIDER]
