<?php

namespace ContainerZXLtxvi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateAdminsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CreateAdminsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CreateAdminsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-admins', [], 'Crée les 3 comptes administrateurs : Hugo, Pierre et Nathan', false, #[\Closure(name: 'App\\Command\\CreateAdminsCommand')] fn (): \App\Command\CreateAdminsCommand => ($container->privates['App\\Command\\CreateAdminsCommand'] ?? $container->load('getCreateAdminsCommandService')));
    }
}
