<?php

namespace ContainerZXLtxvi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGoogleSheetsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\GoogleSheetsController' shared autowired service.
     *
     * @return \App\Controller\GoogleSheetsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/GoogleSheetsController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/GoogleSheetsService.php';

        $container->services['App\\Controller\\GoogleSheetsController'] = $instance = new \App\Controller\GoogleSheetsController(($container->privates['App\\Service\\GoogleSheetsService'] ??= new \App\Service\GoogleSheetsService(\dirname(__DIR__, 4))), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\GoogleSheetsController', $container));

        return $instance;
    }
}
