<?php

namespace ContainerKgXBj0R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_Describers_ConfigService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'nelmio_api_doc.describers.config' shared service.
     *
     * @return \Nelmio\ApiDocBundle\Describer\ExternalDocDescriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/api-doc-bundle/src/Describer/DescriberInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/api-doc-bundle/src/Describer/ExternalDocDescriber.php';

        return $container->privates['nelmio_api_doc.describers.config'] = new \Nelmio\ApiDocBundle\Describer\ExternalDocDescriber(['info' => ['title' => 'M8Pulse API Backend', 'description' => 'API REST Symfony pour un CMS de Data Storytelling avec gestion fine des utilisateurs, articles, blocs, médias, datasets et visualisations', 'version' => '1.0.0'], 'servers' => [['url' => 'http://localhost:8000', 'description' => 'Serveur de développement']], 'tags' => [['name' => 'Authentification', 'description' => 'Connexion, inscription et gestion des tokens'], ['name' => 'Utilisateurs', 'description' => 'Gestion des utilisateurs et profils'], ['name' => 'Articles', 'description' => 'CRUD des articles et publications'], ['name' => 'Blocs', 'description' => 'Gestion des blocs de contenu dans les articles'], ['name' => 'Media', 'description' => 'Upload et gestion des fichiers média'], ['name' => 'Datasets', 'description' => 'Upload et traitement des fichiers CSV'], ['name' => 'Visualisations', 'description' => 'Création et gestion des graphiques'], ['name' => 'Notations', 'description' => 'Système de notation par étoiles'], ['name' => 'Thèmes', 'description' => 'Gestion des thèmes visuels'], ['name' => 'Page d\'\'accueil', 'description' => 'Configuration de la page d\'accueil']], 'components' => ['securitySchemes' => ['Bearer' => ['type' => 'http', 'scheme' => 'bearer', 'bearerFormat' => 'JWT', 'description' => 'JWT Token obtenu via POST /api/login']]], 'security' => [['Bearer' => []]]]);
    }
}
