<?php

namespace ContainerKgXBj0R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PlayerController' shared autowired service.
     *
     * @return \App\Controller\PlayerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PlayerController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/GoogleSheetsService.php';

        $container->services['App\\Controller\\PlayerController'] = $instance = new \App\Controller\PlayerController(($container->privates['App\\Service\\GoogleSheetsService'] ??= new \App\Service\GoogleSheetsService(\dirname(__DIR__, 4))));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\PlayerController', $container));

        return $instance;
    }
}
