services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # Configuration du service Google Sheets
    App\Service\GoogleSheetsService:
        arguments:
            $projectDir: '%kernel.project_dir%'
