<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKgXBj0R\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKgXBj0R/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKgXBj0R.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKgXBj0R\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKgXBj0R\App_KernelDevDebugContainer([
    'container.build_hash' => 'KgXBj0R',
    'container.build_id' => '9e734ec1',
    'container.build_time' => 1765373432,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKgXBj0R');
