<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZXLtxvi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZXLtxvi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZXLtxvi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZXLtxvi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZXLtxvi\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZXLtxvi',
    'container.build_id' => '6859b2fd',
    'container.build_time' => 1767631165,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZXLtxvi');
